### ISSUE TITLE
`annotateCNVtree` function does not work

### ISSUE THREAD

**Issue by kobolock** [must-bioinfo/fastCNV#2]
Hi, 

After using : 
```
tree <- CNVtree(cnv_matrix_clusters)
tree_data <- annotateCNVtree(tree, cnv_matrix_clusters)
```
I have this error :
```
Erreur dans if (anc == 0) break : 
  valeur manquante là où TRUE / FALSE est requis
```

This function uses `get_majorEvents`, `get_cloneEvents`, `get_ancestralEvents`, where are these command in the package ?
```
function (tree, cnv_mat, cnv_thresh = 0.15) 
{
    tree_data <- fortify(tree)
    major_events <- get_majorEvents(cnv_mat, cnv_thresh)
    clone_events <- get_cloneEvents(major_events)
    node_events <- get_ancestralEvents(tree, cnv_mat, major_events)
    if (nrow(clone_events) < 1) {
        return(tree_data)
    }
    if (nrow(node_events) > 1) {
        event_data <- full_join(clone_events, node_events)
    }
    else {
        event_data <- clone_events
    }
    tree_data <- left_join(tree_data, event_data)
    tree_data$events <- sapply(1:nrow(tree_data), .remove_parent_events, 
        tree_data)
    tree_data$events <- sapply(tree_data$events, .aggregate_events)
    tree_data$events[tree_data$events == ""] <- NA_character_
    return(tree_data)
}
<bytecode: 0x000001dd9a5b3d10>
<environment: namespace:fastCNV>
``` 

Best, 

Kobolock

**Comment by csgroen** [comment]
Hello Kobolock,

I can't reproduce this error. Could you provide a minimal reproducible example?

For info, `get_majorEvents`, `get_cloneEvents` and `get_ancestralEvents` are all internals of annotateCNVtree (i.e. not exported), but you can see the source code for them [here](https://github.com/must-bioinfo/fastCNV/blob/master/R/annotateCNVtree.R). However, it seems the error doesn't come from these internals as I can't find the snippet `if (anc == 0)` in them.

**Comment by kobolock** [comment]
Hello Clarice,

So, after using the command `cnv_matrix_clusters <- generateCNVClonesMatrix(seurat_clusterised_PDX, healthyClusters = NULL)`, I save the r object cnv_matrix_clusters in csv format  [here](https://github.com/user-attachments/files/17991935/cnv_matrix_clusters.csv). 
Please, load this file using :
`cnv_matrix_clusters <- as.matrix(read.csv("cnv_matrix_clusters.csv", row.names = 1, check.names = FALSE ))`

After using `annotateCNVtree`: 
```
tree <- CNVtree(cnv_matrix_clusters)
tree_data <- annotateCNVtree(tree, cnv_matrix_clusters)
```
I have this error :
```
Erreur dans if (anc == 0) break : 
  valeur manquante là où TRUE / FALSE est requis
```

Thanks for your help

```
sessionInfo()

R version 4.3.2 (2023-10-31 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 11 x64 (build 22631)

Matrix products: default


locale:
[1] LC_COLLATE=French_France.utf8  LC_CTYPE=French_France.utf8    LC_MONETARY=French_France.utf8 LC_NUMERIC=C                   LC_TIME=French_France.utf8    

time zone: Europe/Paris
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] phangorn_2.11.1    ape_5.7-1          purrr_1.0.2        stringr_1.5.1      ggtree_3.10.0      pheatmap_1.0.12    scales_1.2.1       RColorBrewer_1.1-3 cowplot_1.1.1     
[10] dplyr_1.1.4        ggrepel_0.9.4      ggplot2_3.4.4      Seurat_5.0.1       SeuratObject_5.0.1 sp_2.1-2           DT_0.30            glmGamPoi_1.14.3   fastCNVdata_0.0.3 
[19] fastCNV_0.4
```

**Comment by csgroen** [comment]
Hello,

We've tried reproducing your error in a Windows and Linux system and were not able to do so. 

I've noticed your package versions are older than mine, so maybe updating your packages will make the error go away. Otherwise, you can use trackback to find the culprit and update that specific package.

Let me know if there's anything we can do to help, or when you solve the issue, what was the problem package (maybe we can update the dependency version to make sure it doesn't happen again). I'll leave the issue open for now.

**Comment by kobolock** [comment]
Hi, 

So, here is the `traceback()` result (used after `tree_data <- annotateCNVtree(tree, cnv_matrix_clusters, 0.13)` :
```
8: anc(pvector, node)
7: Ancestors(tree, cnv_combns$V1[i]) at #12
6: intersect(Ancestors(tree, cnv_combns$V1[i]), Ancestors(tree, 
       cnv_combns$V2[i])) at #12
5: FUN(X[[i]], ...)
4: lapply(X = X, FUN = FUN, ...)
3: sapply(1:nrow(cnv_combns), function(i) {
       intersect(Ancestors(tree, cnv_combns$V1[i]), Ancestors(tree, 
           cnv_combns$V2[i]))[1]
   }) at #11
2: get_ancestralEvents(tree, cnv_mat, major_events) at #6
1: annotateCNVtree(tree, cnv_matrix_clusters, 0.13)
```

This indicates that the *Ancestors* function (used to obtain `node_events <- get_ancestralEvents(tree, cnv_mat, major_events)` is being invoked with an invalid argument (cnv_combns$V1[i]), leading to an error.
I replaced the clone names with their indices and so I added in the code :
```
cnv_combns$V1_indices <- match(cnv_combns$V1, tree$tip.label)
cnv_combns$V2_indices <- match(cnv_combns$V2, tree$tip.label)
```
and replaced `cnv_combns$node` command by :
```
cnv_combns$node <- sapply(1:nrow(cnv_combns), function(i) {
    intersect(Ancestors(tree, cnv_combns$V1_indices[i]),
              Ancestors(tree, cnv_combns$V2_indices[i]))[1]
  })
``` 
And now, it works !

**Comment by csgroen** [comment]
Hello,

There should be no need to use indices instead of labels for `Ancestors`, at least in version `phagorn=2.12.1`, where the `Ancestors doc` says:
```
node	an integer **or character vector** (or scalar) corresponding to a node ID
```

But in the interest of keeping it compatible with older versions, we'll add your suggestion with the node id to the latest version.

Best,
Clarice
